version: 2.1
orbs:
  calculator: ryanbourdais/calculator@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - calculator/add:
          numA: 1
          numB: 2
      - run:
          name: Should Equal 3
          command: grep -xq 3 /tmp/ADD_RESULT.txt
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - calculator/calc:
          func: "ADD"
          numA: 1
          numB: 2
          filters: *filters
          post-steps:
            - run: 
                name: Should Equal 3
                command: grep -xq 3 /tmp/ADD_RESULT.txt
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ryanbourdais/calculator
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - calculator/calc
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
